name: 'Test PR'
on:
  pull_request:
    branches:
      - 'master'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-z3-image:
    name: 'Build Z3 Image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: 'Build docker image'
        uses: ./.github/actions/with-docker
        with:
          os: ubuntu
          distro: jammy
          image-tag: runtimeverificationinc/ubuntu-jammy-z3
      - name: 'Push to dockerhub'
        run: |
          version=$(cat version)
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username rvdockerhub --password-stdin
          docker image push runtimeverificationinc/ubuntu-jammy-z3:${version}
